#include <iostream>
#include <random>

using namespace std;

int main()
{
    // random_device rd;
    // mt19937 engine(rd());

    default_random_engine engine; // the simplest engine
    uniform_int_distribution<int> dist(1,6); // Transform the random numbers generated by the engine into a uniform distribution in the range [1, 6]

    // More distributions can be found at https://en.cppreference.com/cpp/named_req/RandomNumberDistribution
    

    for (int i = 0; i < 10; ++i)
    {
        cout << dist(engine) << ' '; // get a value from the distribution using the engine
    }

    cout << '\n';

    return 0;
}

// Try out
// Try to re-implement the program using other random number engines and distributions. You can find a list of engines and distributions at https://en.cppreference.com/w/cpp/numeric/random
